{
 "title": "Dashboard for smartctl_exporter",
 "description": "prometheus-community\r\n/\r\nsmartctl_exporter\r\n",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "SMART General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "smartctl_device_temperature", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "SMART STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_device_smart_status", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Device Critical Warning",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_critical_warning",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power on Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_on_seconds{instance=\"192.168.1.7:9633\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Device Media Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smartctl_device_media_errors", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Power Cycle",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_power_cycle_count",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Error Log Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_error_log_count",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "NVME Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nvme0n1 Data Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "smartctl_device_bytes_written{device=\"nvme0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Spare on NVME",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartctl_device_available_spare{device=\"nvme0\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}